# Generated by Django 5.1.2 on 2024-10-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('posted', 'Submitted by JET'), ('reviewed', 'Submitted by Supervisor'), ('approved_finance', 'Approved by Finance'), ('approved_supervisor', 'Approvided by Supervisor'), ('rejected_finance', 'Rejected by finance'), ('rejected_supervisor', 'Rejected by supervisor')], default='posted', max_length=75)),
                ('type', models.CharField(choices=[('posted', 'Submitted by JET'), ('reviewed', 'Submitted by Supervisor'), ('approved_finance', 'Approved by Finance'), ('approved_supervisor', 'Approvided by Supervisor'), ('rejected_finance', 'Rejected by finance'), ('rejected_supervisor', 'Rejected by supervisor')], max_length=75)),
                ('total', models.IntegerField()),
                ('description', models.TextField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='cycles.cycle')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='files.file')),
            ],
        ),
    ]
