# Generated by Django 5.1.2 on 2024-10-20 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='request',
            name='reviewed_by_finance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='reviewed_by_sup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_sup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('posted', 'Submitted by JET'), ('reviewed', 'Submitted by Supervisor'), ('rejected_supervisor', 'Rejected by supervisor'), ('approved_finance', 'Approved by Finance'), ('rejected_finance', 'Rejected by finance')], default='posted', max_length=75),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('posted', 'Submitted by JET'), ('reviewed', 'Submitted by Supervisor'), ('rejected_supervisor', 'Rejected by supervisor'), ('approved_finance', 'Approved by Finance'), ('rejected_finance', 'Rejected by finance')], max_length=75),
        ),
    ]
