# Generated by Django 5.1.2 on 2024-10-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_request_reviewed_by_finance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finance_comment',
            field=models.CharField(default='This is very good work. If you have any issues, you can reeach out to me', max_length=255),
            preserve_default=False,
        ),
    ]
